# Generated by Django 3.1.7 on 2021-03-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Age', models.IntegerField()),
                ('Careerchoice', models.CharField(choices=[('student', 'STUDENT'), ('Frondend Developer', 'FRONT END DEVELOPER'), ('Backend Developer', 'BACKEND DEVELOPER'), ('Not to say ', 'NOT TO SAY'), ('Other', 'OTHER')], default='Not to say', max_length=18)),
                ('Experience', models.CharField(choices=[('Five', 'FIVE'), ('Four', 'FOUR'), ('Three', 'THREE'), ('Two', 'TWO'), ('One', 'ONE'), ('Zero', 'ZERO')], default='Zero', max_length=6)),
                ('Subcripe', models.BooleanField()),
                ('Feedback', models.TextField()),
            ],
        ),
    ]
