# Generated by Django 3.1.7 on 2021-03-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='Careerchoice',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='Experience',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='Subcripe',
        ),
    ]
