# Generated by Django 3.1.7 on 2021-03-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210305_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='Careerchoice',
            field=models.CharField(choices=[('student', 'STUDENT'), ('Frondend Developer', 'FRONT END DEVELOPER'), ('Backend Developer', 'BACKEND DEVELOPER'), ('Not to say ', 'NOT TO SAY'), ('Other', 'OTHER')], default='Not to say', max_length=18),
        ),
        migrations.AddField(
            model_name='survey',
            name='Experience',
            field=models.CharField(choices=[('Five', 'FIVE'), ('Four', 'FOUR'), ('Three', 'THREE'), ('Two', 'TWO'), ('One', 'ONE'), ('Zero', 'ZERO')], default='Zero', max_length=6),
        ),
    ]
